import turtle
x=int(input('enter your number'))
turtle.left(45)
turtle.forward(x)
turtle.right(90)
turtle.forward(x)
turtle.right(90)
turtle.forward(x)
turtle.right(90)
turtle.forward(x)
turtle.left(135)
turtle.done()
